Repository blinkospace/blinko, pull requests merged in 2024-12, with the labels that each got.

#254 fix: improve mobile
  src/components/BlinkoEditor/index.tsx
  src/components/Common/Div/index.tsx
  src/components/Common/Editor/Toolbar/IconButton/index.tsx
  src/components/Common/Editor/Toolbar/NoteTypeButton/index.tsx
  src/components/Common/Editor/Toolbar/SendButton/index.tsx
  src/components/Common/Editor/Toolbar/ViewModeButton/index.tsx
  src/components/Common/Editor/editorUtils.tsx
  src/components/Common/Editor/type.ts
  src/components/Layout/index.tsx
  src/pages/index.tsx
Labels: size:L

#264 fix: generate thumbnail with orientation
  src/server/plugins/utils.ts
Labels: bug, size:XS

#290 fix some issue
  public/locales/ar/translation.json
  public/locales/de/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/fr/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/pt/translation.json
  public/locales/ru/translation.json
  public/locales/zh-TW/translation.json
  public/locales/zh/translation.json
  src/components/BlinkoCard/cardHeader.tsx
  src/components/BlinkoCard/index.tsx
  src/components/BlinkoCard/noteContent.tsx
  src/components/Common/Editor/editorStore.ts
  src/components/Common/MarkdownRender/Code.tsx
  src/components/Common/MarkdownRender/ListItem.tsx
  src/components/Common/MarkdownRender/index.tsx
  src/components/Common/PopoverFloat/filterPop.tsx
  src/components/Layout/index.tsx
  src/pages/signin.tsx
  src/server/plugins/ai/aiPrompt.ts
  src/server/plugins/memos.ts
  src/server/routers/note.ts
  src/server/routers/tag.ts
  src/store/blinkoStore.tsx
Labels: size:XL

#295 feat: added Azure OpenAI support
  public/locales/ar/translation.json
  public/locales/de/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/fr/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/pt/translation.json
  public/locales/ru/translation.json
  public/locales/tr/translation.json
  public/locales/zh-TW/translation.json
  public/locales/zh/translation.json
  src/components/BlinkoSettings/AiSetting.tsx
  src/server/plugins/ai/aiModelFactory.ts
  src/server/plugins/ai/azureOpenAIModelProvider.ts
  src/server/types.ts
  src/store/aiStore.tsx
Labels: enhancement, size:L

#305 fix: Enhanced the context handling in the AI service by concatenating…
  app/api/s3file/[...filename]/route.ts
  src/server/plugins/ai.ts
Labels: size:XS

#316 refactor: change mdx editor to veditor
  next.config.js
  package.json
  pnpm-lock.yaml
  public/locales/ar/translation.json
  public/locales/de/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/fr/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/pt/translation.json
  public/locales/ru/translation.json
  public/locales/tr/translation.json
  public/locales/zh-TW/translation.json
  public/locales/zh/translation.json
  src/components/BlinkoAddButton/index.tsx
  src/components/BlinkoCard/index.tsx
  src/components/BlinkoEditor/index.tsx
  src/components/BlinkoRightClickMenu/index.tsx
  src/components/Common/Editor/EditorToolbar/extends.ts
  src/components/Common/Editor/EditorToolbar/i18n.ts
  src/components/Common/Editor/EditorToolbar/index.ts
  src/components/Common/Editor/Toolbar/HashtagButton/index.tsx
  src/components/Common/Editor/Toolbar/IconButton/index.tsx
  src/components/Common/Editor/Toolbar/ReferenceButton/index.tsx
  src/components/Common/Editor/Toolbar/SendButton/index.tsx
  src/components/Common/Editor/Toolbar/ViewModeButton/index.tsx
  src/components/Common/Editor/editorPlugins.tsx
  src/components/Common/Editor/editorStore.ts
  src/components/Common/Editor/editorUtils.tsx
  src/components/Common/Editor/hooks/useEditor.ts
  src/components/Common/Editor/index.tsx
  src/components/Common/Editor/type.ts
  src/components/Common/MdxPlugin/hashTagPlugin/index.ts
  src/components/Common/PopoverFloat/index.tsx
  src/components/Common/PopoverFloat/tagSelectPop.tsx
  src/components/Common/TipsDialog/index.tsx
  src/components/Layout/index.tsx
  src/lib/hooks.ts
  src/pages/_app.tsx
  src/pages/index.tsx
  src/server/routers/note.ts
  src/store/aiStore.tsx
  src/store/blinkoStore.tsx
  src/store/user.ts
  src/styles/editor.css
  src/styles/github-markdown.css
  src/styles/globals.css
  src/styles/vditor.css
Labels: size:XXL

#317 fix: enhance file upload handling and editor integration
  app/api/file/upload/route.ts
  src/components/BlinkoMultiSelectPop/index.tsx
  src/components/Common/Editor/editorStore.ts
  src/components/Common/Editor/hooks/useEditor.ts
  src/pages/resources.tsx
  src/pages/review.tsx
  src/styles/vditor.css
Labels: size:L

#319 fix: style
  public/locales/zh-TW/translation.json
  public/locales/zh/translation.json
  src/components/Common/Editor/EditorToolbar/i18n.ts
  src/components/Common/Editor/EditorToolbar/index.ts
  src/components/Common/Editor/hooks/useEditor.ts
  src/components/Layout/index.tsx
Labels: size:M

#322 fix: some issue
  app/api/file/[...filename]/route.ts
  app/api/file/upload/route.ts
  src/components/BlinkoCard/blogContent.tsx
  src/components/Common/AttachmentRender/imageRender.tsx
  src/components/Common/AttachmentRender/index.tsx
  src/components/Common/Editor/editorStore.ts
  src/components/Common/Editor/index.tsx
  src/components/Common/MarkdownRender/LinkPreview.tsx
  src/components/Common/MarkdownRender/index.tsx
  src/components/Common/PopoverFloat/aiWritePop.tsx
  src/components/Layout/index.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  src/server/plugins/ai.ts
  src/server/plugins/ai/aiPrompt.ts
  src/store/baseStore.ts
  src/store/blinkoStore.tsx
  src/store/module/Dialog/Provider.tsx
Labels: size:L

#329 feat: support delete user & batch delete note
  public/locales/ar/translation.json
  public/locales/de/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/fr/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/pt/translation.json
  public/locales/ru/translation.json
  public/locales/tr/translation.json
  public/locales/zh-TW/translation.json
  public/locales/zh/translation.json
  src/components/BlinkoSettings/UserSetting.tsx
  src/components/Common/TipsDialog/index.tsx
  src/components/Layout/index.tsx
  src/pages/signin.tsx
  src/server/routers/note.ts
  src/server/routers/user.ts
Labels: size:L

#330 fix: support file upload loading tips
  app/api/file/upload/route.ts
  public/locales/ar/translation.json
  public/locales/de/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/fr/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/pt/translation.json
  public/locales/ru/translation.json
  public/locales/tr/translation.json
  public/locales/zh-TW/translation.json
  public/locales/zh/translation.json
  public/manifest.json
  src/components/BlinkoSettings/BasicSetting.tsx
  src/components/BlinkoSettings/ImportSetting.tsx
  src/components/BlinkoSettings/StorageSetting.tsx
  src/components/Common/Editor/editorStore.tsx
  src/components/Common/TipsDialog/index.tsx
  src/components/Common/UploadFile/index.tsx
  src/pages/index.tsx
  src/pages/signin.tsx
  src/server/plugins/files.ts
  src/server/routers/user.ts
  src/store/blinkoStore.tsx
  src/store/module/Toast/Toast.tsx
  src/store/user.ts
Labels: released, size:L

#336 improve some code
  package.json
  pnpm-lock.yaml
  prisma/migrations/20241218023101_0_27_0/migration.sql
  prisma/schema.prisma
  src/components/BlinkoAi/index.tsx
  src/components/Common/AttachmentRender/DraggableFileGrid.tsx
  src/components/Common/AttachmentRender/icons.tsx
  src/components/Common/AttachmentRender/imageRender.tsx
  src/components/Common/AttachmentRender/index.tsx
  src/components/Common/Editor/editorStore.tsx
  src/components/Common/Editor/index.tsx
  src/components/Common/PopoverFloat/filterPop.tsx
  src/components/Layout/BarSearchInput.tsx
  src/components/Layout/MobileNavBar.tsx
  src/components/Layout/Sidebar.tsx
  src/components/Layout/index.tsx
  src/lib/prismaZodType.ts
  src/server/routers/note.ts
  src/store/baseStore.ts
  src/store/module/Dialog/Provider.tsx
  src/store/module/DialogStandalone/Provider.tsx
  src/store/standard/StorageState.ts
  src/store/user.ts
Labels: size:XL

#347 fix: german translations
  public/locales/de/translation.json
Labels: size:L

#351 Refactor resouce
  next.config.js
  package.json
  prisma/migrations/20241219062514_0_27_7/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
  public/locales/ar/translation.json
  public/locales/de/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/fr/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/pt/translation.json
  public/locales/ru/translation.json
  public/locales/tr/translation.json
  public/locales/zh-TW/translation.json
  public/locales/zh/translation.json
  src/components/BlinkoResource/ResourceContextMenu.tsx
  src/components/BlinkoResource/ResourceItem.tsx
  src/components/BlinkoRightClickMenu/index.tsx
  src/components/BlinkoSettings/StorageSetting.tsx
  src/components/Common/AttachmentRender/DraggableFileGrid.tsx
  src/components/Common/AttachmentRender/FileIcon.tsx
  src/components/Common/AttachmentRender/index.tsx
  src/components/Common/LoadingAndEmpty.tsx
  src/components/Layout/index.tsx
  src/lib/constant.ts
  src/lib/prismaZodType.ts
  src/pages/index.tsx
  src/pages/resources.tsx
  src/server/plugins/files.ts
  src/server/routers/attachment.ts
  src/server/routers/note.ts
  src/server/types.ts
  src/store/blinkoStore.tsx
  src/store/resourceStore.tsx
  src/store/standard/PromiseState.ts
Labels: size:XXL

#352 fix: build issue
  app/api/file/[...filename]/route.ts
  next.config.js
  src/components/BlinkoResource/ResourceContextMenu.tsx
  src/server/plugins/ai.ts
  src/server/plugins/ai/openAIModelProvider.ts
  src/server/plugins/files.ts
Labels: size:M

#354 Music
  package.json
  pnpm-lock.yaml
  public/locales/ar/translation.json
  public/locales/de/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/fr/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/pt/translation.json
  public/locales/ru/translation.json
  public/locales/tr/translation.json
  public/locales/zh-TW/translation.json
  public/locales/zh/translation.json
  src/components/BlinkoMusicPlayer/index.tsx
  src/components/BlinkoResource/ResourceItem.tsx
  src/components/BlinkoSettings/Item.tsx
  src/components/BlinkoSettings/MusicSetting.tsx
  src/components/Common/AttachmentRender/audioRender.tsx
  src/components/Common/AttachmentRender/index.tsx
  src/components/Common/Editor/editorStore.tsx
  src/lib/constant.ts
  src/pages/_app.tsx
  src/pages/api/trpc/[trpc].ts
  src/pages/settings.tsx
  src/server/routers/helper/spotify.ts
  src/server/routers/public.ts
  src/server/types.ts
  src/store/index.ts
  src/store/musicManagerStore.tsx
Labels: enhancement, size:XXL

#370 feat: support analytics page
  pnpm-lock.yaml
  public/locales/ar/translation.json
  public/locales/de/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/fr/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/pt/translation.json
  public/locales/ru/translation.json
  public/locales/tr/translation.json
  public/locales/zh-TW/translation.json
  public/locales/zh/translation.json
  src/components/BlinkoAnalytics/HeatMap.tsx
  src/components/BlinkoAnalytics/StatsCards.tsx
  src/components/BlinkoAnalytics/TagDistributionChart.tsx
  src/pages/analytics.tsx
  src/server/routers/_app.ts
  src/server/routers/analytics.ts
  src/store/analyticsStore.ts
  src/store/baseStore.ts
Labels: enhancement, size:XL

#377 Offline support
  next.config.js
  package.json
  pnpm-lock.yaml
  prisma/seed.ts
  prisma/seedData.ts
  public/fallback-development.js
  public/locales/ar/translation.json
  public/locales/de/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/fr/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/pt/translation.json
  public/locales/ru/translation.json
  public/locales/tr/translation.json
  public/locales/zh-TW/translation.json
  public/locales/zh/translation.json
  src/components/BlinkoCard/cardFooter.tsx
  src/components/BlinkoMultiSelectPop/index.tsx
  src/components/Layout/index.tsx
  src/lib/hooks.ts
  src/pages/_offline.tsx
  src/pages/index.tsx
  src/server/routers/user.ts
  src/store/baseStore.ts
  src/store/blinkoStore.tsx
  src/store/standard/PromiseState.ts
  src/styles/github-markdown.css
Labels: enhancement, size:XL

#378 dev
  next.config.js
  package.json
  pnpm-lock.yaml
  public/locales/ar/translation.json
  public/locales/de/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/fr/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/pt/translation.json
  public/locales/ru/translation.json
  public/locales/tr/translation.json
  public/locales/zh-TW/translation.json
  public/locales/zh/translation.json
  src/components/BlinkoAnalytics/HeatMap.tsx
  src/components/BlinkoCard/index.tsx
  src/components/BlinkoSettings/MusicSetting.tsx
  src/components/BlinkoSettings/PerferSetting.tsx
  src/components/Common/GradientBackground.tsx
  src/pages/share/[id].tsx
  src/pages/signin.tsx
  src/pages/signup.tsx
  src/server/types.ts
  src/styles/globals.css
  tailwind.config.js
Labels: size:XL

#388 sso support
  next.config.js
  prisma/migrations/20241231014246_0_32_0/migration.sql
  prisma/schema.prisma
  public/locales/ar/translation.json
  public/locales/de/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/fr/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/pt/translation.json
  public/locales/ru/translation.json
  public/locales/tr/translation.json
  public/locales/zh-TW/translation.json
  public/locales/zh/translation.json
  src/components/BlinkoSettings/AboutSetting.tsx
  src/components/BlinkoSettings/SSOSetting.tsx
  src/components/Layout/index.tsx
  src/pages/api/auth/[...nextauth].ts
  src/pages/oauth-callback.tsx
  src/pages/settings.tsx
  src/pages/signin.tsx
  src/server/routers/public.ts
  src/server/trpc.ts
  src/server/types.ts
  src/store/user.ts
Labels: size:XXL

#392 fix: add theme color customization and update translations
  public/locales/ar/translation.json
  public/locales/de/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/fr/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/pt/translation.json
  public/locales/ru/translation.json
  public/locales/tr/translation.json
  public/locales/zh-TW/translation.json
  public/locales/zh/translation.json
  src/components/BlinkoSettings/PerferSetting.tsx
  src/components/Common/Theme/ThemeColor.tsx
  src/components/Common/Theme/ThemeSwitcher.tsx
  src/pages/signin.tsx
  src/server/types.ts
  src/store/user.ts
Labels: size:L
