Repository blinkospace/blinko, pull requests merged in 2025-03, with the labels that each got.

#520 fix(ai): Add support for additional embedding dimensions in AiModelF…
  src/components/BlinkoSettings/PerferSetting.tsx
  src/server/plugins/ai/aiModelFactory.ts
Labels: enhancement, size:M

#534 Bug fix
  app/api/rss/[userId]/atom/route.ts
  app/api/rss/[userId]/rss/route.ts
  next.config.js
  src/server/plugins/ai.ts
  src/server/plugins/rebuildEmbeddingJob.ts
  src/server/routers/helper/index.ts
Labels: size:M

#539 fix: build
  app/api/rss/[userId]/atom/route.ts
  app/api/rss/[userId]/rss/route.ts
  public/fallback-nqfYkN-Ghrh61V6XfmXs9.js
Labels: size:XS

#535 fix: Railway requires Blinko to listen on 0.0.0.0
  dockerfile
Labels: bug, size:XS

#537 fix(translations): Update french translation
  public/locales/fr/translation.json
Labels: size:M

#544 fix(plugin-manager): correct plugin setting panel flag assignment
  src/store/plugin/pluginManagerStore.ts
Labels: bug, size:XS

#542 Update Turkish Translation
  public/locales/tr/translation.json
Labels: documentation, size:XL

#546 Articule cover image based on markdown content (cover image) if no explicit cover is provided
  src/components/BlinkoCard/cardBlogBox.tsx
Labels: enhancement, size:S

#549 Fix bug
  package.json
  pnpm-lock.yaml
  public/locales/ar/translation.json
  public/locales/de/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/fr/translation.json
  public/locales/ja/translation.json
  public/locales/ka/translation.json
  public/locales/ko/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/ru/translation.json
  public/locales/tr/translation.json
  public/locales/zh-TW/translation.json
  public/locales/zh/translation.json
  src/components/BlinkoFollowDialog/index.tsx
  src/components/BlinkoResource/ResourceItem.tsx
  src/components/Common/AttachmentRender/index.tsx
  src/components/Common/BlinkoSelectNote/index.tsx
  src/components/Common/Editor/Toolbar/ResourceReferenceButton/index.tsx
  src/components/Common/Editor/editorStore.tsx
  src/components/Common/Editor/index.tsx
  src/server/routers/note.ts
  src/server/routers/public.ts
Labels: size:XL

#550 fix: refactor search input
  public/fallback-gPoowoUDMcYj_hHF8wflR.js
  public/locales/ar/translation.json
  public/locales/de/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/fr/translation.json
  public/locales/ja/translation.json
  public/locales/ka/translation.json
  public/locales/ko/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/ru/translation.json
  public/locales/tr/translation.json
  public/locales/zh-TW/translation.json
  public/locales/zh/translation.json
  src/components/BlinkoCard/cardFooter.tsx
  src/components/BlinkoResource/ResourceItem.tsx
  src/components/Common/BlinkoSelectNote/index.tsx
  src/components/Common/Editor/Toolbar/ResourceReferenceButton/index.tsx
  src/components/Common/ScrollableTabs/index.tsx
  src/components/Layout/BarSearchInput.tsx
  src/components/Layout/GlobalSearch.tsx
  src/components/Layout/index.tsx
  src/pages/settings.tsx
  src/store/blinkoStore.tsx
Labels: size:XXL

#557 Fix bug
  package.json
  pnpm-lock.yaml
  public/fallback-QF-h8-zwDqp4f22SFpTab.js
  public/locales/ar/translation.json
  public/locales/de/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/fr/translation.json
  public/locales/ja/translation.json
  public/locales/ka/translation.json
  public/locales/ko/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/ru/translation.json
  public/locales/tr/translation.json
  public/locales/zh-TW/translation.json
  public/locales/zh/translation.json
  src/components/BlinkoAi/aiInput.tsx
  src/components/BlinkoMultiSelectPop/index.tsx
  src/components/BlinkoSettings/AiSetting.tsx
  src/components/BlinkoSettings/HttpProxySetting.tsx
  src/components/Common/Editor/EditorToolbar/i18n.ts
  src/components/Layout/BarSearchInput.tsx
  src/pages/plugin.tsx
  src/pages/settings.tsx
  src/server/plugins/ai.ts
  src/server/plugins/ai/aiModelFactory.ts
  src/server/plugins/ai/providers/anthropic.ts
  src/server/plugins/ai/providers/azureOpenAI.ts
  src/server/plugins/ai/providers/deepseek.ts
  src/server/plugins/ai/providers/gemini.ts
  src/server/plugins/ai/providers/grok.ts
  src/server/plugins/ai/providers/index.ts
  src/server/plugins/ai/providers/ollama.ts
  src/server/plugins/ai/providers/openAI.ts
  src/server/plugins/ai/providers/openRouter.ts
  src/server/plugins/ai/providers/voyage.ts
  src/server/routers/ai.ts
  src/server/routers/helper/proxy.ts
  src/server/routers/helper/spotify.ts
  src/server/routers/note.ts
  src/server/routers/plugin.ts
  src/server/routers/public.ts
  src/server/types.ts
  src/store/baseStore.ts
Labels: size:XXL

#560 Fix bug
  src/components/BlinkoSettings/PluginSetting.tsx
  src/server/routers/ai.ts
  src/store/aiStore.tsx
  src/store/plugin/pluginManagerStore.ts
Labels: size:M

#576 Fix bug
  blinko-types/package.json
  next.config.js
  public/fallback-QF-h8-zwDqp4f22SFpTab.js
  public/locales/ar/translation.json
  public/locales/de/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/fr/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/ru/translation.json
  public/locales/tr/translation.json
  public/locales/zh-TW/translation.json
  public/locales/zh/translation.json
  src/components/BlinkoAddButton/index.tsx
  src/components/BlinkoCard/index.tsx
  src/components/BlinkoEditor/index.tsx
  src/components/BlinkoSettings/AiSetting.tsx
  src/components/BlinkoSettings/PluginSetting.tsx
  src/components/Common/Editor/Toolbar/ResourceReferenceButton/index.tsx
  src/components/Common/Editor/Toolbar/SendButton/index.tsx
  src/components/Common/Editor/editorStore.tsx
  src/components/Common/Editor/index.tsx
  src/components/Common/Editor/type.ts
  src/components/Layout/GlobalSearch.tsx
  src/lib/utils/versionUtils.ts
  src/pages/api/trpc/[trpc].ts
  src/server/plugins/ai.ts
  src/server/plugins/ai/aiModelFactory.ts
  src/server/plugins/rebuildEmbeddingJob.ts
  src/server/routers/ai.ts
  src/server/routers/helper/index.ts
  src/server/routers/note.ts
  src/server/routers/plugin.ts
  src/store/aiStore.tsx
  src/store/blinkoStore.tsx
  src/store/plugin/pluginApiStore.tsx
  src/store/plugin/pluginManagerStore.ts
  src/store/plugin/pluginRender.tsx
  src/store/standard/PromiseState.ts
Labels: size:XL

#581 major system optimization
  DEV.md
  app/api/file/[...filename]/route.ts
  app/api/file/upload/route.ts
  dockerfile
  index.html
  next.config.js
  package.json
  pnpm-lock.yaml
  prisma/schema.prisma
  prisma/seed.ts
  public/locales/ar/translation.json
  public/locales/de/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/fr/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/ru/translation.json
  public/locales/tr/translation.json
  public/locales/zh-TW/translation.json
  public/locales/zh/translation.json
  src/components/BlinkoAi/aiChatBox.tsx
  src/components/BlinkoSettings/AiSetting.tsx
  src/components/BlinkoSettings/TaskSetting.tsx
  src/components/Common/AudioRecorder/index.tsx
  src/components/Common/Editor/Toolbar/ViewModeButton/index.tsx
  src/components/Common/Editor/editorStore.tsx
  src/components/Common/Editor/hooks/useEditor.ts
  src/components/Common/RebuildEmbeddingProgress/index.tsx
  src/lib/cache.ts
  src/lib/trpc.ts
  src/server/plugins/ai.ts
  src/server/plugins/ai/aiModelFactory.ts
  src/server/plugins/ai/providers/index.ts
  src/server/plugins/ai/tools/updateBlinko.ts
  src/server/plugins/ai/vector/filter.ts
  src/server/plugins/ai/vector/index.ts
  src/server/plugins/ai/vector/libsql-config/api.ts
  src/server/plugins/ai/vector/libsql-config/config.ts
  src/server/plugins/ai/vector/libsql-config/uri.ts
  src/server/plugins/ai/vector/libsql-config/util.ts
  src/server/plugins/ai/vector/sql-builder.ts
  src/server/plugins/ai/vector/sqlite3.ts
  src/server/plugins/dbjob.ts
  src/server/plugins/files.ts
  src/server/plugins/rebuildEmbeddingJob.ts
  src/server/plugins/recommandJob.ts
  src/server/routers/_app.ts
  src/server/routers/ai.ts
  src/server/routers/follows.ts
  src/server/routers/helper/index.ts
  src/server/routers/plugin.ts
  src/server/types.ts
  src/store/blinkoStore.tsx
  src/styles/vditor.css
Labels: size:XL

#583 fix: delete tags and botes button undelete tags Issue || fix: delete tags and bottles button undelete tags Issue
  src/server/routers/tag.ts
Labels: bug, size:XS

#584 fix: Tooltip component display problems
  src/components/BlinkoSettings/AiSetting.tsx
  src/components/BlinkoSettings/HttpProxySetting.tsx
  src/components/BlinkoSettings/Item.tsx
Labels: bug, size:L

#585 Dutch translation
  public/locales/nl/translation.json
Labels: enhancement, size:XL

#586 fix: decode filename from binary to UTF-8 in file upload
  app/api/file/upload/route.ts
Labels: bug, size:XS

#590 feat: support internal sharing and multi-person collaboration
  prisma/migrations/20250331072252_0_48_0/migration.sql
  prisma/schema.prisma
  public/locales/ar/translation.json
  public/locales/de/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/fr/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/nl/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/ru/translation.json
  public/locales/tr/translation.json
  public/locales/zh-TW/translation.json
  public/locales/zh/translation.json
  src/components/BlinkoShareDialog/index.tsx
  src/components/Common/Editor/editorStore.tsx
  src/components/Common/Iconify/icons.tsx
  src/components/Layout/index.tsx
  src/lib/prismaZodType.ts
  src/pages/review.tsx
  src/server/routers/note.ts
  src/server/routers/user.ts
  src/server/types.ts
  src/store/blinkoStore.tsx
Labels: size:XXL
