Repository blinkospace/blinko, pull requests merged in 2025-01, with the labels that each got.

#394 Fix bug #371
  src/components/Common/Editor/editorStore.tsx
  src/components/Common/Editor/index.tsx
Labels: bug, size:S

#404 Update de/translation.json
  public/locales/de/translation.json
Labels: size:M

#409 Trash Notes instead of deleting when deleting Tag
  src/server/routers/tag.ts
Labels: enhancement, size:XS

#412 feat: support RSS
  app/api/rss/[userId]/atom/route.ts
  app/api/rss/[userId]/rss/route.ts
  package.json
  pnpm-lock.yaml
  src/components/BlinkoCard/cardHeader.tsx
  src/server/routers/public.ts
Labels: size:L

#413 fix: move generateFeed function to helper module
  app/api/rss/[userId]/atom/route.ts
  app/api/rss/[userId]/rss/route.ts
  src/server/routers/helper/index.ts
Labels: size:L

#416 feat: add comments feature 🎉
  package.json
  pnpm-lock.yaml
  prisma/migrations/20250108081202_0_34_0/migration.sql
  prisma/schema.prisma
  public/locales/ar/translation.json
  public/locales/de/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/fr/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/pt/translation.json
  public/locales/ru/translation.json
  public/locales/tr/translation.json
  public/locales/zh-TW/translation.json
  public/locales/zh/translation.json
  src/components/BlinkoCard/cardFooter.tsx
  src/components/BlinkoCard/cardHeader.tsx
  src/components/BlinkoCard/commentButton.tsx
  src/components/BlinkoSettings/BasicSetting.tsx
  src/components/BlinkoShareDialog/index.tsx
  src/components/Common/Editor/EditorToolbar/extends.ts
  src/components/Common/Editor/editorStore.tsx
  src/components/Common/Editor/hooks/useEditor.ts
  src/components/Common/Editor/index.tsx
  src/components/Common/ScrollArea/index.tsx
  src/components/Common/UploadFile/index.tsx
  src/lib/prismaZodType.ts
  src/server/context.ts
  src/server/plugins/ai.ts
  src/server/plugins/ai/aiPrompt.ts
  src/server/routers/_app.ts
  src/server/routers/ai.ts
  src/server/routers/comment.ts
  src/server/routers/note.ts
  src/server/routers/user.ts
  src/server/types.ts
Labels: enhancement, size:XL

#421 Fix #417 the maximum width status of the home page being saved
  src/components/BlinkoSettings/PerferSetting.tsx
Labels: bug, size:XS

#422 enhancement 390 When tagging an article with ai, it is automatically selected as the tag post.
  src/components/BlinkoAi/aiTag.tsx
Labels: enhancement, size:XS

#428 fix #323 scheduled backup cannot be performed automatically
  src/lib/helper.ts
  src/server/plugins/archivejob.ts
  src/server/plugins/baseScheduleJob.ts
  src/server/plugins/dbjob.ts
  src/server/routers/task.ts
  src/store/blinkoStore.tsx
Labels: bug, enhancement, size:L

#429 fix #427 The picture in the input box cannot be deleted
  src/components/Common/AttachmentRender/icons.tsx
  src/store/blinkoStore.tsx
  src/store/standard/StorageListState.ts
Labels: bug, released, size:S

#434 fix #430 Chat history persisting between different user accounts
  src/store/aiStore.tsx
  src/store/blinkoStore.tsx
Labels: bug, size:S

#436 remove console log
  src/store/aiStore.tsx
  src/store/blinkoStore.tsx
Labels: size:XS

#437 fix #435 Just deleting tags will mess up the note format
  src/server/routers/tag.ts
Labels: bug, size:XS

#440 Create polish translation.json
  public/locales/pl/translation.json
Labels: size:L

#441 Update README.md with new live demo link and Railway deployment button
  README.md
Labels: size:XS

#446 fix #444 Editing a ‘Note’ that’s selected when viewing by tag changes the note to a Blinko
  src/components/BlinkoEditor/index.tsx
  src/components/Common/Editor/Toolbar/NoteTypeButton/index.tsx
  src/components/Common/Editor/editorStore.tsx
  src/components/Common/Editor/hooks/useEditor.ts
  src/components/Common/Editor/index.tsx
  src/components/Common/Editor/type.ts
  src/server/types.ts
Labels: bug, size:M

#448 fix #363 多级待办UI显示错误 || fix #363 Multi-level to-do UI display error
  src/components/Common/MarkdownRender/ListItem.tsx
Labels: bug, size:S

#451 fix: add embedding API configuration and update translations
  public/locales/ar/translation.json
  public/locales/de/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/fr/translation.json
  public/locales/ja/translation.json
  public/locales/ko/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/ru/translation.json
  public/locales/tr/translation.json
  public/locales/zh-TW/translation.json
  public/locales/zh/translation.json
  src/components/BlinkoSettings/AiSetting.tsx
  src/components/BlinkoSettings/Item.tsx
  src/server/plugins/ai/azureOpenAIModelProvider.ts
  src/server/plugins/ai/ollamaModelProvider.ts
  src/server/plugins/ai/openAIModelProvider.ts
  src/server/types.ts
Labels: size:L

#454 Create translation.json
  public/locales/ka/translation.json
  src/store/baseStore.ts
Labels: documentation, size:L
