Repository blinkospace/blinko, pull requests merged in 2025-04, with the labels that each got.

#595 fix(memos): add missing type field in notes upsert, set default value…
  src/server/plugins/memos.ts
Labels: bug, size:XS

#594 Added the function of unselecting all and updating the translation on the resource page; Content in the trash doesn't display a share button
  public/locales/de/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/fr/translation.json
  public/locales/ja/translation.json
  public/locales/ka/translation.json
  public/locales/ko/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/ru/translation.json
  public/locales/tr/translation.json
  public/locales/zh-TW/translation.json
  public/locales/zh/translation.json
  src/components/BlinkoRightClickMenu/index.tsx
  src/pages/resources.tsx
Labels: enhancement, size:M

#600 Update Dutch language
  public/locales/nl/translation.json
  src/store/baseStore.ts
Labels: size:XXL

#596 fix(memos): reimport memos notes, If the notes have not been modified…
  src/server/plugins/memos.ts
Labels: bug, size:XS

#602 fix: emit event to exit full screen mode after send.related issue: #501
  src/components/Common/Editor/editorStore.tsx
Labels: bug, released, size:XS

#605 fix: conditionally render button based on daily review configuration
  src/components/Layout/index.tsx
Labels: bug, size:XS

#606 fix(/ai): Behavior of the Enter key when using Chinese input method
  src/components/BlinkoAi/aiInput.tsx
Labels: bug, size:XS

#609 feat: cards show internal sharing icons. related issue: #604
  public/locales/ar/translation.json
  public/locales/de/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/fr/translation.json
  public/locales/ja/translation.json
  public/locales/ka/translation.json
  public/locales/ko/translation.json
  public/locales/nl/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/ru/translation.json
  public/locales/tr/translation.json
  public/locales/zh-TW/translation.json
  public/locales/zh/translation.json
  src/components/BlinkoCard/cardHeader.tsx
  src/components/BlinkoNoteHistory/HistoryButton.tsx
  src/server/routers/note.ts
Labels: enhancement, released, size:L

#624 feat(BlinkoAddButton): When the H5 bottom bar appears, move the bottom up slightly to avoid being obscured.
  src/components/BlinkoAddButton/index.tsx
Labels: enhancement, size:XS

#625 fix(BlinktoAddButton): #619,Hide the previous editing and AI buttons
  src/components/BlinkoAddButton/index.tsx
Labels: bug, released, size:M

#627 Bug fix
  app/api/completions/route.ts
  next.config.js
  package.json
  public/locales/ar/translation.json
  public/locales/de/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/fr/translation.json
  public/locales/ja/translation.json
  public/locales/ka/translation.json
  public/locales/ko/translation.json
  public/locales/nl/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/ru/translation.json
  public/locales/tr/translation.json
  public/locales/zh-TW/translation.json
  public/locales/zh/translation.json
  src/components/BlinkoSettings/AiSetting.tsx
  src/components/BlinkoSettings/BasicSetting.tsx
  src/components/BlinkoSettings/UserSetting.tsx
  src/components/Common/Editor/index.tsx
  src/components/Common/UserAvatarDropdown.tsx
  src/server/context.ts
  src/server/plugins/ai.ts
  src/server/plugins/ai/aiModelFactory.ts
  src/server/routers/user.ts
  src/server/trpc.ts
  src/server/types.ts
Labels: bug, size:XXL

#628 fix(H5 Add Button): can not jump to AI when no AI is used
  src/components/BlinkoAddButton/index.tsx
Labels: bug, released, size:XS

#645 fix: Solve AI to add tags, cannot use custom prompts
  src/server/routers/ai.ts
Labels: bug, released, size:XS

#650 Update en translation
  public/locales/en/translation.json
  src/components/BlinkoSettings/BasicSetting.tsx
Labels: size:M

#666 Ensures that the ollama path for the list of models is `/api/tags`
  app/src/components/BlinkoSettings/AiSetting.tsx
Labels: bug, released, size:XS
