Repository blinkospace/blinko, pull requests merged in 2025-09, with the labels that each got.

#877 feat:imporve desktop
  .claude/settings.local.json
  .cursor/rules/coding-standards.mdc
  .cursor/rules/frontend-development-guide.mdc
  .cursor/rules/project-structure.mdc
  .gitignore
  .kilocode/mcp.json
  CLAUDE.md
  app/package.json
  app/public/locales/ar/translation.json
  app/public/locales/de/translation.json
  app/public/locales/en/translation.json
  app/public/locales/es/translation.json
  app/public/locales/fr/translation.json
  app/public/locales/ja/translation.json
  app/public/locales/ka/translation.json
  app/public/locales/kab/translation.json
  app/public/locales/ko/translation.json
  app/public/locales/nl/translation.json
  app/public/locales/pl/translation.json
  app/public/locales/pt/translation.json
  app/public/locales/ru/translation.json
  app/public/locales/tr/translation.json
  app/public/locales/zh-TW/translation.json
  app/public/locales/zh/translation.json
  app/src-tauri/Cargo.lock
  app/src-tauri/Cargo.toml
  app/src-tauri/capabilities/default.json
  app/src-tauri/src/desktop/autostart.rs
  app/src-tauri/src/desktop/hotkey.rs
  app/src-tauri/src/desktop/mod.rs
  app/src-tauri/src/desktop/setup.rs
  app/src-tauri/src/desktop/text_selection.rs
  app/src-tauri/src/desktop/tray.rs
  app/src-tauri/src/desktop/window.rs
  app/src-tauri/src/desktop/window_state.rs
  app/src-tauri/src/lib.rs
  app/src-tauri/tauri.conf.json
  app/src/App.tsx
  app/src/components/BlinkoAi/aiInput.tsx
  app/src/components/BlinkoEditor/index.tsx
  app/src/components/BlinkoSettings/HotkeySetting.tsx
  app/src/components/Common/Editor/index.tsx
  app/src/components/Layout/index.tsx
  app/src/hooks/useInitialHotkeySetup.ts
  app/src/hooks/useQuickaiHotkey.ts
  app/src/hooks/useQuicknoteHotkey.ts
  app/src/pages/quickai.tsx
  app/src/pages/quicknote.tsx
  app/src/pages/quicktool.tsx
  app/src/pages/settings.tsx
  app/src/store/aiStore.tsx
  app/src/styles/globals.css
  bun.lock
  shared/lib/types.ts
Labels: size:XXL

#884 fix: prevent empty string being sent to embeddings API
  server/routerTrpc/note.ts
Labels: bug, size:S

#891 Fix bug
  .claude/settings.local.json
  app/package.json
  app/src-tauri/Cargo.lock
  app/src-tauri/Cargo.toml
  app/src-tauri/capabilities/default.json
  app/src-tauri/gen/android/app/src/main/AndroidManifest.xml
  app/src-tauri/gen/android/app/src/main/java/com/blinko/app/MainActivity.kt
  app/src-tauri/src/desktop/autostart.rs
  app/src-tauri/src/desktop/mod.rs
  app/src-tauri/src/desktop/setup.rs
  app/src-tauri/src/lib.rs
  app/src/components/BlinkoAddButton/index.tsx
  app/src/components/BlinkoAi/aiChatBox.tsx
  app/src/components/BlinkoCard/noteContent.tsx
  app/src/components/BlinkoEditor/index.tsx
  app/src/components/BlinkoRightClickMenu/index.tsx
  app/src/components/BlinkoSettings/AiSetting.tsx
  app/src/components/BlinkoSettings/HotkeySetting.tsx
  app/src/components/Common/Editor/index.tsx
  app/src/components/Common/MarkdownRender/index.tsx
  app/src/components/Layout/BarSearchInput.tsx
  app/src/components/Layout/GlobalSearch.tsx
  app/src/lib/hooks.ts
  app/src/pages/ai.tsx
  app/src/store/blinkoStore.tsx
  app/src/styles/github-markdown.css
  bun.lock
  server/routerTrpc/note.ts
  server/routerTrpc/user.ts
Labels: size:XL
