Repository blinkospace/blinko, pull requests merged in 2025-02, with the labels that each got.

#475 fix(ai): Preserve original updatedAt timestamp during memos import and reindexing
  src/server/plugins/ai.ts
  src/server/plugins/memos.ts
  src/server/routers/note.ts
Labels: bug, size:M

#482 Feat(memos) support correct import comments
  src/server/plugins/memos.ts
Labels: enhancement, size:L

#484 Fix(server/config) custom background url not work
  src/server/routers/config.ts
Labels: bug, size:XS

#483 fix(note): FE accidentally turned into blinko after operating on note
  src/server/routers/note.ts
  src/store/blinkoStore.tsx
Labels: bug, size:XS

#502 fix #495 task marke complete in dashboard
  src/components/Common/MarkdownRender/ListItem.tsx
Labels: bug, released, size:L

#504 Plugin system
  .gitignore
  blinko-types/package.json
  next.config.js
  package.json
  pnpm-lock.yaml
  prisma/migrations/20250219083523_0_39_0/migration.sql
  prisma/schema.prisma
  public/fallback-6rKSH48JzcW6GolBGUWEK.js
  public/locales/ar/translation.json
  public/locales/de/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/fr/translation.json
  public/locales/ja/translation.json
  public/locales/ka/translation.json
  public/locales/ko/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/ru/translation.json
  public/locales/tr/translation.json
  public/locales/zh-TW/translation.json
  public/locales/zh/translation.json
  src/components/BlinkoRightClickMenu/index.tsx
  src/components/BlinkoSettings/PluginSetting.tsx
  src/components/Common/Editor/Toolbar/AIWriteButton/index.tsx
  src/components/Common/Editor/Toolbar/IconButton/index.tsx
  src/components/Common/Editor/index.tsx
  src/lib/prismaZodType.ts
  src/pages/_app.tsx
  src/pages/index.tsx
  src/pages/settings.tsx
  src/server/plugins/ai.ts
  src/server/routers/_app.ts
  src/server/routers/attachment.ts
  src/server/routers/config.ts
  src/server/routers/plugin.ts
  src/server/types.ts
  src/store/plugin/index.ts
  src/store/plugin/pluginApiStore.tsx
  src/store/plugin/pluginManagerStore.ts
  src/store/plugin/pluginRender.tsx
  tsconfig.types.json
Labels: size:XL

#506 merge main change to branch Feature/npm taobao mirror and chinese prompts
  .gitignore
  CHANGELOG.md
  blinko-types/package.json
  next.config.js
  package.json
  pnpm-lock.yaml
  prisma/migrations/20250219083523_0_39_0/migration.sql
  prisma/schema.prisma
  public/fallback-M6zu_8kcos4ZIMgAVOKwv.js
  public/locales/ar/translation.json
  public/locales/de/translation.json
  public/locales/en/translation.json
  public/locales/es/translation.json
  public/locales/fr/translation.json
  public/locales/ja/translation.json
  public/locales/ka/translation.json
  public/locales/ko/translation.json
  public/locales/pl/translation.json
  public/locales/pt/translation.json
  public/locales/ru/translation.json
  public/locales/tr/translation.json
  public/locales/zh-TW/translation.json
  public/locales/zh/translation.json
  src/components/BlinkoMultiSelectPop/index.tsx
  src/components/BlinkoNotification/index.tsx
  src/components/BlinkoResource/ResourceMultiSelectpop.tsx
  src/components/BlinkoRightClickMenu/index.tsx
  src/components/BlinkoSettings/AiSetting.tsx
  src/components/BlinkoSettings/PluginSetting.tsx
  src/components/Common/Editor/Toolbar/AIWriteButton/index.tsx
  src/components/Common/Editor/Toolbar/IconButton/index.tsx
  src/components/Common/Editor/index.tsx
  src/components/Common/LoadingAndEmpty.tsx
  src/components/Common/MarkdownRender/ListItem.tsx
  src/components/Common/MultiSelectToolbar.tsx
  src/lib/prismaZodType.ts
  src/pages/_app.tsx
  src/pages/api/serve-plugin/[...path].ts
  src/pages/index.tsx
  src/pages/resources.tsx
  src/pages/settings.tsx
  src/server/plugins/ai.ts
  src/server/routers/_app.ts
  src/server/routers/attachment.ts
  src/server/routers/config.ts
  src/server/routers/helper/index.ts
  src/server/routers/plugin.ts
  src/server/types.ts
  src/store/plugin/index.ts
  src/store/plugin/pluginApiStore.tsx
  src/store/plugin/pluginManagerStore.ts
  src/store/plugin/pluginRender.tsx
  src/store/resourceStore.tsx
  src/store/user.ts
  tsconfig.types.json
Labels: size:XXL
